import { EstagioObra } from './estagio-obra';
import { FotoImovel } from './foto-imovel.interface';
import { SituacaoEmpreendimento } from './situacao-empreendimento';
import { TipoImovel } from './tipo-imovel';
import { TipoPadraoImovel } from './tipo-padrao-imovel';

export interface Imovel {
  id: number;
  codigoReferenciaImovel: string;
  nomeImovel: string;
  preco: number;
  precoLocacao: number;
  endereco: string;
  numero: string;
  areaterreno: string;
  nquartos: string;
  nsuites: string;
  ngaragens: string;
  fotodestaque: number;
  destaque: string;
  destaquebanner: string;
  localizacao: string;
  complemento: string;
  descricao: string;
  nomeBairro: string;
  nomeCidade: string;
  siglaEstado: string;
  nomeEstado: string;
  dataCadastroImovel: string;
  atualizadoem: string;
  dataAtualizacaoFotos: string;
  caracteristicasImovelList: string[];
  caracteristicasEmpreendimentoList: string[];
  urlCustom: string;
  urlFotoDestaque: string;
  tipoImovel: TipoImovel;
  tipoPadraoImovel?: TipoPadraoImovel;
  fotoImovelList: FotoImovel[];
  tourVirtual?: string;
  paraVenda?: boolean;
  paraLocacao?: boolean;
  novos?: boolean;
  usados?: boolean;
  estagioObra?: EstagioObra;
  situacaoEmpreendimento?: SituacaoEmpreendimento;
}
